/**
 * Amazigh Symbol Data
 * Each symbol has trilingual metadata (French + English + Tifinagh)
 */

const SYMBOLS = [
  {
    id: 'yaz',
    name: 'Yaz',
    nameEn: 'Yaz',
    tifinagh: 'ⵢⴰⵣ',
    meaning: 'Homme libre',
    meaningEn: 'Free Man',
    meaningTifinagh: 'ⴰⵎⴰⵣⵉⵖ ⵉⵍⴻⵍⵍⵉ',
    description: "Le Yaz (ⵣ) est le symbole identitaire le plus emblématique du peuple amazigh. Sa forme évoque un homme debout, bras levés vers le ciel, exprimant la liberté et la résistance. Adopté comme emblème pan-amazigh, il figure sur le drapeau amazigh aux côtés des couleurs bleu, vert et jaune.",
    descriptionEn: "The Yaz (ⵣ) is the most emblematic identity symbol of the Amazigh people. Its shape evokes a standing man with arms raised to the sky, expressing freedom and resistance. Adopted as the pan-Amazigh emblem, it appears on the Amazigh flag alongside the blue, green, and yellow colors.",
    descriptionTifinagh: "ⵢⴰⵣ ⴷ ⴰⵣⴰⵎⵓⵍ ⵏ ⵜⵎⴰⵣⵉⵖⵜ. ⴰⵔ ⵉⵙⵙⴽⵜⵉ ⵜⵉⵍⴻⵍⵍⵉ ⴷ ⵓⵎⵏⵖⵉ.",
    svgId: 'yaz'
  },
  {
    id: 'tanit',
    name: 'Tanit',
    nameEn: 'Tanit',
    tifinagh: 'ⵜⴰⵏⵉⵜ',
    meaning: 'Déesse de la fertilité',
    meaningEn: 'Goddess of Fertility',
    meaningTifinagh: 'ⵜⴰⵎⵖⴰⵔⵜ ⵏ ⵜⵓⵙⵓⵜ',
    description: "Tanit est une déesse majeure de la mythologie amazighe et punique. Son symbole — un triangle surmonté d'un cercle avec une barre horizontale — représente le corps féminin, la fertilité et la fécondité. On le retrouve abondamment sur les stèles et poteries antiques d'Afrique du Nord.",
    descriptionEn: "Tanit is a major goddess of Amazigh and Punic mythology. Her symbol — a triangle topped with a circle and a horizontal bar — represents the female body, fertility, and fecundity. It is found abundantly on ancient steles and pottery of North Africa.",
    descriptionTifinagh: "ⵜⴰⵏⵉⵜ ⴷ ⵜⴰⵎⵖⴰⵔⵜ ⵜⴰⵎⵇⵇⵔⴰⵏⵜ ⴳ ⵜⵎⵉⵜⵓⵍⵓⵊⵉⵜ ⵜⴰⵎⴰⵣⵉⵖⵜ.",
    svgId: 'tanit'
  },
  {
    id: 'losange',
    name: 'Losange',
    nameEn: 'Diamond',
    tifinagh: 'ⵜⴰⵎⵖⴰⵔⵜ',
    meaning: 'Féminité et fécondité',
    meaningEn: 'Femininity and Fertility',
    meaningTifinagh: 'ⵜⴰⵎⵟⵟⵓⵜ ⴷ ⵜⵓⵙⵓⵜ',
    description: "Le losange est l'un des motifs les plus récurrents de l'art amazigh. Il symbolise la féminité, le ventre maternel et la fécondité. Souvent imbriqué en séries, il orne les tapis, les poteries et les tatouages faciaux traditionnels des femmes amazighes.",
    descriptionEn: "The diamond is one of the most recurring patterns in Amazigh art. It symbolizes femininity, the maternal womb, and fertility. Often interlocking in series, it adorns carpets, pottery, and the traditional facial tattoos of Amazigh women.",
    descriptionTifinagh: "ⵜⴰⵎⵖⴰⵔⵜ ⴷ ⵓⵏⵓⵖ ⵉⵜⵜⵓⵙⴰⵏⵏ ⴳ ⵜⵥⵓⵕⵉ ⵜⴰⵎⴰⵣⵉⵖⵜ.",
    svgId: 'losange'
  },
  {
    id: 'chevrons',
    name: 'Chevrons',
    nameEn: 'Chevrons',
    tifinagh: 'ⴰⵎⴰⵏ',
    meaning: "L'eau, source de vie",
    meaningEn: 'Water, Source of Life',
    meaningTifinagh: 'ⴰⵎⴰⵏ, ⴰⵖⴱⴰⵍⵓ ⵏ ⵜⵓⴷⴻⵔⵜ',
    description: "Les chevrons en zigzag symbolisent l'eau et les cours d'eau dans l'art amazigh. Présents en lignes parallèles sur les tapis et les poteries, ils évoquent la pluie, les rivières et la fertilité de la terre. L'eau étant sacrée dans la culture amazighe, ce motif est omniprésent.",
    descriptionEn: "The zigzag chevrons symbolize water and waterways in Amazigh art. Found in parallel lines on carpets and pottery, they evoke rain, rivers, and the fertility of the land. Water being sacred in Amazigh culture, this pattern is omnipresent.",
    descriptionTifinagh: "ⵉⵛⴻⴱⵔⵓⵏⴻⵏ ⴰⵔ ⵙⵎⴻⴽⵜⵉⵏ ⴰⵎⴰⵏ ⴷ ⵜⵓⴷⴻⵔⵜ.",
    svgId: 'chevrons'
  },
  {
    id: 'oeil',
    name: 'Œil',
    nameEn: 'Eye',
    tifinagh: 'ⵜⵉⵟⵟ',
    meaning: 'Protection contre le mauvais œil',
    meaningEn: 'Protection Against the Evil Eye',
    meaningTifinagh: 'ⴰⵏⴻⵥⵕⵓⴼ ⵙⴻⴳ ⵜⵉⵟⵟ ⵏ ⵓⴼⵓⵙ',
    description: "L'œil est un puissant symbole protecteur dans la culture amazighe. Représenté de face, il est censé renvoyer le mauvais œil et protéger son porteur. On le retrouve tatoué sur les visages, gravé sur les portes et brodé sur les textiles pour éloigner le malheur.",
    descriptionEn: "The eye is a powerful protective symbol in Amazigh culture. Depicted facing forward, it is meant to reflect the evil eye and protect its bearer. It is found tattooed on faces, carved on doors, and embroidered on textiles to ward off misfortune.",
    descriptionTifinagh: "ⵜⵉⵟⵟ ⴷ ⴰⵣⴰⵎⵓⵍ ⵏ ⵓⵏⴻⵥⵕⵓⴼ ⴳ ⵜⴷⴻⵍⵙⴰ ⵜⴰⵎⴰⵣⵉⵖⵜ.",
    svgId: 'oeil'
  },
  {
    id: 'serpent',
    name: 'Serpent / Zigzag',
    nameEn: 'Serpent / Zigzag',
    tifinagh: 'ⴰⵣⵔⵎ',
    meaning: 'Protection et renaissance',
    meaningEn: 'Protection and Rebirth',
    meaningTifinagh: 'ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵜⴰⵍⴰⵍⵉⵜ ⵜⴰⵎⴰⵢⵏⵓⵜ',
    description: "Le zigzag symbolise le serpent, créature sacrée dans la cosmologie amazighe. Le serpent représente la renaissance (par sa mue), la protection du foyer et la sagesse. Les motifs en zigzag sur les poteries et les murs des maisons servent de gardiens spirituels.",
    descriptionEn: "The zigzag symbolizes the serpent, a sacred creature in Amazigh cosmology. The serpent represents rebirth (through shedding its skin), protection of the home, and wisdom. Zigzag patterns on pottery and house walls serve as spiritual guardians.",
    descriptionTifinagh: "ⴰⵣⵔⵎ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⴰⵍⴰⵍⵉⵜ ⵜⴰⵎⴰⵢⵏⵓⵜ ⴷ ⵓⵏⴻⵥⵕⵓⴼ.",
    svgId: 'serpent'
  },
  {
    id: 'croix',
    name: 'Croix d\'Agadez',
    nameEn: 'Cross of Agadez',
    tifinagh: 'ⵜⴰⵣⵍⵎⴰⴹⵜ',
    meaning: 'Équilibre et points cardinaux',
    meaningEn: 'Balance and Cardinal Points',
    meaningTifinagh: 'ⴰⵎⵙⴰⵙⴰ ⴷ ⵜⵉⵙⴽⵉⵡⵉⵏ',
    description: "La croix berbère — souvent appelée croix d'Agadez chez les Touaregs — symbolise les quatre points cardinaux et l'équilibre cosmique. Chaque pointe est ornée d'un losange, représentant l'ouverture aux quatre directions du monde. C'est un bijou emblématique de l'orfèvrerie amazighe.",
    descriptionEn: "The Berber cross — often called the Cross of Agadez among the Tuareg — symbolizes the four cardinal points and cosmic balance. Each tip is adorned with a diamond, representing openness to the four directions of the world. It is an emblematic jewel of Amazigh craftsmanship.",
    descriptionTifinagh: "ⵜⴰⵣⵍⵎⴰⴹⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⵎⵙⴰⵙⴰ ⴷ ⵜⵉⵙⴽⵉⵡⵉⵏ ⵏ ⵓⵎⴰⴹⴰⵍ.",
    svgId: 'croix'
  },
  {
    id: 'fibule',
    name: 'Fibule',
    nameEn: 'Fibula',
    tifinagh: 'ⵜⵉⵙⴻⵔⵏⵉⵏ',
    meaning: 'Union et lien conjugal',
    meaningEn: 'Union and Marital Bond',
    meaningTifinagh: 'ⵜⴰⵢⵔⵉ ⴷ ⵓⵎⵢⴰⵙⵙⴰ',
    description: "La fibule (tisernin) est une broche triangulaire utilisée pour attacher les vêtements traditionnels amazighs. Portée par paire reliée par une chaîne, elle symbolise l'union du couple et le lien conjugal. C'est aussi un bijou de prestige offert lors des mariages.",
    descriptionEn: "The fibula (tisernin) is a triangular brooch used to fasten traditional Amazigh clothing. Worn in pairs connected by a chain, it symbolizes the union of the couple and the marital bond. It is also a prestigious jewel gifted during weddings.",
    descriptionTifinagh: "ⵜⵉⵙⴻⵔⵏⵉⵏ ⴷ ⴰⵣⴰⵎⵓⵍ ⵏ ⵜⴰⵢⵔⵉ ⴷ ⵓⵎⵢⴰⵙⵙⴰ.",
    svgId: 'fibule'
  },
  {
    id: 'khamsa',
    name: 'Khamsa',
    nameEn: 'Khamsa',
    tifinagh: 'ⵜⴰⴼⵓⵙⵜ',
    meaning: 'Main protectrice',
    meaningEn: 'Protective Hand',
    meaningTifinagh: 'ⴰⴼⵓⵙ ⵏ ⵓⵏⴻⵥⵕⵓⴼ',
    description: "La Khamsa (main ouverte) est un symbole protecteur universel en Afrique du Nord. Les cinq doigts repoussent le mauvais œil. Souvent ornée d'un œil central, elle est gravée sur les portes, portée en pendentif et tatouée sur les mains des femmes amazighes.",
    descriptionEn: "The Khamsa (open hand) is a universal protective symbol in North Africa. The five fingers repel the evil eye. Often adorned with a central eye, it is carved on doors, worn as a pendant, and tattooed on the hands of Amazigh women.",
    descriptionTifinagh: "ⵜⴰⴼⵓⵙⵜ ⴰⵔ ⵜⵏⴻⵥⵕⵓⴼ ⵙⴻⴳ ⵜⵉⵟⵟ ⵏ ⵓⴼⵓⵙ.",
    svgId: 'khamsa'
  },
  {
    id: 'etoile',
    name: 'Étoile à 8 branches',
    nameEn: 'Eight-Pointed Star',
    tifinagh: 'ⵉⵜⵔⵉ',
    meaning: 'Guidance et destin',
    meaningEn: 'Guidance and Destiny',
    meaningTifinagh: 'ⴰⵏⴻⴳⵎⵓ ⴷ ⵉⵅⴼ',
    description: "L'étoile à huit branches est un motif central des tapis amazighs. Elle symbolise la guidance, le destin et l'orientation. Les huit pointes représentent les directions intermédiaires entre les points cardinaux, offrant une protection complète à 360 degrés.",
    descriptionEn: "The eight-pointed star is a central pattern in Amazigh carpets. It symbolizes guidance, destiny, and orientation. The eight points represent the intermediate directions between the cardinal points, offering complete 360-degree protection.",
    descriptionTifinagh: "ⵉⵜⵔⵉ ⵙ ⵜⴰⵎ ⵏ ⵉⵥⵓⵕⴰⵏ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⴰⵏⴻⴳⵎⵓ.",
    svgId: 'etoile'
  },
  {
    id: 'peigne',
    name: 'Peigne',
    nameEn: 'Comb',
    tifinagh: 'ⵜⴰⵎⵛⴹⵜ',
    meaning: 'Beauté et tissage',
    meaningEn: 'Beauty and Weaving',
    meaningTifinagh: 'ⵜⴰⵥⵓⵕⵉ ⴷ ⵓⵣⴻⵟⵟⴰ',
    description: "Le peigne est un symbole de beauté et de féminité dans l'art amazigh. Il représente aussi le métier à tisser, activité sacrée des femmes amazighes. Le peigne tatoué sur le front ou le menton était un signe de beauté et de statut social.",
    descriptionEn: "The comb is a symbol of beauty and femininity in Amazigh art. It also represents the loom, a sacred activity of Amazigh women. The comb tattooed on the forehead or chin was a sign of beauty and social status.",
    descriptionTifinagh: "ⵜⴰⵎⵛⴹⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⵜⴰⵥⵓⵕⵉ ⴷ ⵓⵣⴻⵟⵟⴰ.",
    svgId: 'peigne'
  },
  {
    id: 'ciseaux',
    name: 'Ciseaux',
    nameEn: 'Scissors',
    tifinagh: 'ⵜⵉⵎⵇⴰⵙⵉⵏ',
    meaning: 'Coupure du mal',
    meaningEn: 'Cutting Evil',
    meaningTifinagh: 'ⴰⴱⴻⵜⵜⵓ ⵏ ⵓⴼⵓⵙ',
    description: "Les ciseaux symbolisent la coupure avec le mal et les énergies négatives. Placés ouverts sous l'oreiller d'un nouveau-né ou gravés sur les murs, ils sont censés couper les liens avec les forces maléfiques et protéger les plus vulnérables.",
    descriptionEn: "Scissors symbolize cutting ties with evil and negative energies. Placed open under a newborn's pillow or carved on walls, they are meant to sever links with malevolent forces and protect the most vulnerable.",
    descriptionTifinagh: "ⵜⵉⵎⵇⴰⵙⵉⵏ ⴰⵔ ⵙⴱⴻⵜⵜⵓⵏⵜ ⴰⴼⵓⵙ ⴷ ⵜⵉⵖⵔⵙⵉⵡⵉⵏ.",
    svgId: 'ciseaux'
  },
  {
    id: 'lezard',
    name: 'Lézard',
    nameEn: 'Lizard',
    tifinagh: 'ⵜⴰⵣⴰⵔⵎⵉⵎⵜ',
    meaning: 'Quête de lumière',
    meaningEn: 'Quest for Light',
    meaningTifinagh: 'ⴰⵔⵣⵣⵓ ⵏ ⵜⴰⴼⵓⴽⵜ',
    description: "Le lézard est un animal symbolique fort dans la culture amazighe. Toujours tourné vers le soleil, il représente la quête de lumière, de chaleur et de connaissance. On le retrouve sur les poteries kabyles et les murs des villages, souvent stylisé en formes géométriques.",
    descriptionEn: "The lizard is a powerful symbolic animal in Amazigh culture. Always turned toward the sun, it represents the quest for light, warmth, and knowledge. It is found on Kabyle pottery and village walls, often stylized in geometric forms.",
    descriptionTifinagh: "ⵜⴰⵣⴰⵔⵎⵉⵎⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⵔⵣⵣⵓ ⵏ ⵜⴰⴼⵓⴽⵜ.",
    svgId: 'lezard'
  },
  {
    id: 'poisson',
    name: 'Poisson',
    nameEn: 'Fish',
    tifinagh: 'ⴰⵙⵍⵎ',
    meaning: 'Abondance et prospérité',
    meaningEn: 'Abundance and Prosperity',
    meaningTifinagh: 'ⵜⴰⴳⴳⴰⵔⵜ ⴷ ⵓⵙⴻⵖⴷ',
    description: "Le poisson symbolise l'abondance, la prospérité et la fertilité dans la culture amazighe. Présent sur les poteries et les décorations domestiques, il est associé à l'eau vivifiante et à la générosité de la nature. C'est aussi un porte-bonheur traditionnel.",
    descriptionEn: "The fish symbolizes abundance, prosperity, and fertility in Amazigh culture. Found on pottery and domestic decorations, it is associated with life-giving water and nature's generosity. It is also a traditional good luck charm.",
    descriptionTifinagh: "ⴰⵙⵍⵎ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⴰⴳⴳⴰⵔⵜ ⴷ ⵓⵙⴻⵖⴷ.",
    svgId: 'poisson'
  },
  {
    id: 'arbre',
    name: 'Arbre de vie',
    nameEn: 'Tree of Life',
    tifinagh: 'ⵜⴰⵙⴻⴽⵍⴰ ⵏ ⵜⵓⴷⴻⵔⵜ',
    meaning: 'Lignée et enracinement',
    meaningEn: 'Lineage and Rootedness',
    meaningTifinagh: 'ⵜⴰⵡⵊⴰ ⴷ ⵉⵥⵓⵕⴰⵏ',
    description: "L'arbre de vie représente la lignée familiale, les racines ancestrales et la continuité entre les générations. Ses branches symbolisent les descendants et ses racines les ancêtres. C'est un motif central des tapis de l'Atlas et des broderies traditionnelles.",
    descriptionEn: "The tree of life represents family lineage, ancestral roots, and continuity between generations. Its branches symbolize descendants and its roots the ancestors. It is a central pattern in Atlas carpets and traditional embroideries.",
    descriptionTifinagh: "ⵜⴰⵙⴻⴽⵍⴰ ⵏ ⵜⵓⴷⴻⵔⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⵜⴰⵡⵊⴰ ⴷ ⵉⵥⵓⵕⴰⵏ.",
    svgId: 'arbre'
  },
  {
    id: 'triangle',
    name: 'Triangle',
    nameEn: 'Triangle',
    tifinagh: 'ⴰⵎⴽⵓⵥ',
    meaning: 'Fertilité et matrice de vie',
    meaningEn: 'Fertility and Matrix of Life',
    meaningTifinagh: 'ⵜⵓⵙⵓⵜ ⴷ ⵜⴰⵎⴰⵜⴰⵔⵜ ⵏ ⵜⵓⴷⴻⵔⵜ',
    description: "Le triangle est l'une des formes les plus anciennes de l'art amazigh. Pointe vers le haut, il représente le masculin et le feu ; pointe vers le bas, il symbolise le féminin, le ventre maternel et la fertilité. Souvent combiné en séries, il orne les tapis, les poteries et les tatouages faciaux.",
    descriptionEn: "The triangle is one of the oldest forms in Amazigh art. Point up, it represents the masculine and fire; point down, it symbolizes the feminine, the maternal womb, and fertility. Often combined in series, it adorns carpets, pottery, and facial tattoos.",
    descriptionTifinagh: "ⴰⵎⴽⵓⵥ ⴷ ⵢⴰⵜ ⵙⴻⴳ ⵜⵖⴰⵔⴰⵙⵉⵏ ⵜⵉⵇⴱⵓⵔⵉⵏ ⴳ ⵜⵥⵓⵕⵉ ⵜⴰⵎⴰⵣⵉⵖⵜ.",
    svgId: 'triangle'
  },
  {
    id: 'spirale',
    name: 'Spirale',
    nameEn: 'Spiral',
    tifinagh: 'ⵜⴰⵡⵓⵔⵉ',
    meaning: 'Cycle éternel de la vie',
    meaningEn: 'Eternal Cycle of Life',
    meaningTifinagh: 'ⴰⵙⵓⴼⵖ ⵏ ⵜⵓⴷⴻⵔⵜ',
    description: "La spirale est un motif universel présent dans l'art amazigh depuis le néolithique. Elle symbolise le cycle éternel de la vie, la mort et la renaissance. On la retrouve gravée sur les rochers du Sahara, sur les poteries et les tapis, évoquant le mouvement perpétuel de l'existence.",
    descriptionEn: "The spiral is a universal pattern found in Amazigh art since the Neolithic era. It symbolizes the eternal cycle of life, death, and rebirth. Found carved on Saharan rocks, on pottery and carpets, it evokes the perpetual movement of existence.",
    descriptionTifinagh: "ⵜⴰⵡⵓⵔⵉ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⵙⵓⴼⵖ ⴰⵎⴳⴳⴰⵔⵓ ⵏ ⵜⵓⴷⴻⵔⵜ.",
    svgId: 'spirale'
  },
  {
    id: 'soleil',
    name: 'Soleil',
    nameEn: 'Sun',
    tifinagh: 'ⵜⴰⴼⵓⴽⵜ',
    meaning: 'Vie, énergie et éveil',
    meaningEn: 'Life, Energy and Awakening',
    meaningTifinagh: 'ⵜⵓⴷⴻⵔⵜ, ⵜⴰⵣⵎⴻⵔⵜ ⴷ ⵜⴰⵏⴻⴽⵔⴰ',
    description: "Le soleil est un symbole central de la cosmologie amazighe. Il représente la vie, l'énergie, la chaleur et le renouveau quotidien. Dessiné sous forme de cercle avec des rayons, il est omniprésent sur les tapis, poteries et bijoux. Le soleil incarne aussi la connaissance et l'éveil spirituel.",
    descriptionEn: "The sun is a central symbol in Amazigh cosmology. It represents life, energy, warmth, and daily renewal. Drawn as a circle with rays, it is omnipresent on carpets, pottery, and jewelry. The sun also embodies knowledge and spiritual awakening.",
    descriptionTifinagh: "ⵜⴰⴼⵓⴽⵜ ⴷ ⴰⵣⴰⵎⵓⵍ ⴰⵎⵇⵇⵔⴰⵏ ⴳ ⵜⴷⴻⵍⵙⴰ ⵜⴰⵎⴰⵣⵉⵖⵜ.",
    svgId: 'soleil'
  },
  {
    id: 'lune',
    name: 'Croissant de lune',
    nameEn: 'Crescent Moon',
    tifinagh: 'ⴰⵢⵢⵓⵔ',
    meaning: 'Renouveau et cycles féminins',
    meaningEn: 'Renewal and Feminine Cycles',
    meaningTifinagh: 'ⵜⴰⵍⴰⵍⵉⵜ ⵜⴰⵎⴰⵢⵏⵓⵜ ⴷ ⵉⵙⵓⴼⵖⴻⵏ',
    description: "Le croissant de lune symbolise la matière qui naît, grandit et meurt pour renaître. Il représente les cycles féminins, le renouveau et la guidance nocturne. Souvent associé à l'étoile dans les bijoux amazighs, il est un symbole de protection et de féminité sacrée.",
    descriptionEn: "The crescent moon symbolizes matter that is born, grows, and dies to be reborn. It represents feminine cycles, renewal, and nocturnal guidance. Often associated with the star in Amazigh jewelry, it is a symbol of protection and sacred femininity.",
    descriptionTifinagh: "ⴰⵢⵢⵓⵔ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵉⵙⵓⴼⵖⴻⵏ ⴷ ⵜⴰⵍⴰⵍⵉⵜ ⵜⴰⵎⴰⵢⵏⵓⵜ.",
    svgId: 'lune'
  },
  {
    id: 'oiseau',
    name: 'Oiseau / Hirondelle',
    nameEn: 'Bird / Swallow',
    tifinagh: 'ⴰⴳⴹⵉⴹ',
    meaning: 'Liberté et bénédictions',
    meaningEn: 'Freedom and Blessings',
    meaningTifinagh: 'ⵜⵉⵍⴻⵍⵍⵉ ⴷ ⵜⵉⵔⵉⵡⵉⵏ',
    description: "L'oiseau — et particulièrement l'hirondelle — symbolise la liberté, les bénédictions divines et les messages spirituels. L'hirondelle tatouée sur le front des femmes amazighes était un signe de beauté et de féminité. Les oiseaux en vol sur les tapis représentent l'âme libérée.",
    descriptionEn: "The bird — and particularly the swallow — symbolizes freedom, divine blessings, and spiritual messages. The swallow tattooed on the forehead of Amazigh women was a sign of beauty and femininity. Birds in flight on carpets represent the liberated soul.",
    descriptionTifinagh: "ⴰⴳⴹⵉⴹ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⵉⵍⴻⵍⵍⵉ ⴷ ⵜⵉⵔⵉⵡⵉⵏ ⵏ ⵕⴻⴱⴱⵉ.",
    svgId: 'oiseau'
  },
  {
    id: 'palmier',
    name: 'Palmier',
    nameEn: 'Palm Tree',
    tifinagh: 'ⵜⴰⵣⴷⴰⵢⵜ',
    meaning: 'Fertilité, richesse et maternité',
    meaningEn: 'Fertility, Wealth and Motherhood',
    meaningTifinagh: 'ⵜⵓⵙⵓⵜ, ⴰⵖⵔⴻⴼ ⴷ ⵜⴰⵎⴰⵜⴰⵔⵜ',
    description: "Le palmier est un symbole de fertilité, de richesse et de générosité dans la culture amazighe. Le tronc tatoué sur le menton des femmes — notamment dans les Aurès et au Maroc — représente la mère, pilier de la famille. Ses palmes évoquent la protection et ses dattes l'abondance.",
    descriptionEn: "The palm tree is a symbol of fertility, wealth, and generosity in Amazigh culture. The trunk tattooed on women's chins — particularly in the Aures and Morocco — represents the mother, pillar of the family. Its fronds evoke protection and its dates abundance.",
    descriptionTifinagh: "ⵜⴰⵣⴷⴰⵢⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⵜⵓⵙⵓⵜ ⴷ ⵓⵖⵔⴻⴼ.",
    svgId: 'palmier'
  },
  {
    id: 'belier',
    name: 'Bélier',
    nameEn: 'Ram',
    tifinagh: 'ⵉⴽⴻⵔⵔⵉ',
    meaning: 'Force, vie et générosité',
    meaningEn: 'Strength, Life and Generosity',
    meaningTifinagh: 'ⵜⴰⵣⵎⴻⵔⵜ, ⵜⵓⴷⴻⵔⵜ ⴷ ⵜⴰⵎⴻⵍⵍⴰ',
    description: "Le bélier est un symbole puissant de force physique, de vie et de générosité dans la mythologie amazighe. Animal sacré depuis l'Antiquité — les gravures rupestres du Sahara montrent des béliers à sphéroïde — il symbolise aussi le sacrifice, la virilité et la protection du troupeau.",
    descriptionEn: "The ram is a powerful symbol of physical strength, life, and generosity in Amazigh mythology. A sacred animal since antiquity — Saharan rock engravings show rams with spheroids — it also symbolizes sacrifice, virility, and protection of the flock.",
    descriptionTifinagh: "ⵉⴽⴻⵔⵔⵉ ⴷ ⴰⵣⴰⵎⵓⵍ ⵏ ⵜⴰⵣⵎⴻⵔⵜ ⴷ ⵜⵓⴷⴻⵔⵜ.",
    svgId: 'belier'
  },
  {
    id: 'scorpion',
    name: 'Scorpion',
    nameEn: 'Scorpion',
    tifinagh: 'ⵜⴰⵖⵔⴷⴰⵢⵜ',
    meaning: 'Protection et défense',
    meaningEn: 'Protection and Defense',
    meaningTifinagh: 'ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵓⵎⵏⵖⵉ',
    description: "Le scorpion est un symbole de protection et de défense dans la culture amazighe. Tatoué ou gravé, il est censé repousser les forces maléfiques par sa dangerosité même. Sa capacité à survivre dans les conditions les plus hostiles en fait un emblème de résilience et de résistance.",
    descriptionEn: "The scorpion is a symbol of protection and defense in Amazigh culture. Tattooed or carved, it is meant to repel malevolent forces through its very dangerousness. Its ability to survive in the most hostile conditions makes it an emblem of resilience and resistance.",
    descriptionTifinagh: "ⵜⴰⵖⵔⴷⴰⵢⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵓⵎⵏⵖⵉ.",
    svgId: 'scorpion'
  },
  {
    id: 'grenouille',
    name: 'Grenouille',
    nameEn: 'Frog',
    tifinagh: 'ⴰⵎⵇⴻⵔⵇⵓⵔ',
    meaning: 'Magie et fertilité',
    meaningEn: 'Magic and Fertility',
    meaningTifinagh: 'ⴰⵙⵃⵓⵔ ⴷ ⵜⵓⵙⵓⵜ',
    description: "La grenouille est associée à la magie et à la fertilité dans les croyances amazighes. Liée à l'eau et à la pluie, elle symbolise la transformation et le renouveau. Dans certaines régions, elle figure dans les rites de fertilité et les pratiques magiques liées à la fécondité.",
    descriptionEn: "The frog is associated with magic and fertility in Amazigh beliefs. Linked to water and rain, it symbolizes transformation and renewal. In some regions, it appears in fertility rites and magical practices related to fecundity.",
    descriptionTifinagh: "ⴰⵎⵇⴻⵔⵇⵓⵔ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⴰⵙⵃⵓⵔ ⴷ ⵜⵓⵙⵓⵜ.",
    svgId: 'grenouille'
  },
  {
    id: 'araignee',
    name: 'Araignée',
    nameEn: 'Spider',
    tifinagh: 'ⵜⵉⵙⵙⵉⵜ',
    meaning: 'Tissage et rites magiques',
    meaningEn: 'Weaving and Magical Rites',
    meaningTifinagh: 'ⴰⵣⴻⵟⵟⴰ ⴷ ⵉⵙⵃⵓⵔⴻⵏ',
    description: "L'araignée symbolise le tissage — activité sacrée des femmes amazighes — et les rites magiques. Sa toile représente la création patiente, le destin et les liens invisibles entre les êtres. Elle est aussi associée à la fertilité et à la protection du foyer par ses pouvoirs mystiques.",
    descriptionEn: "The spider symbolizes weaving — a sacred activity of Amazigh women — and magical rites. Its web represents patient creation, destiny, and invisible bonds between beings. It is also associated with fertility and protection of the home through its mystical powers.",
    descriptionTifinagh: "ⵜⵉⵙⵙⵉⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⵣⴻⵟⵟⴰ ⴷ ⵉⵙⵃⵓⵔⴻⵏ.",
    svgId: 'araignee'
  },
  {
    id: 'sablier',
    name: 'Sablier',
    nameEn: 'Hourglass',
    tifinagh: 'ⵜⴰⵙⵙⴰⵄⵜ',
    meaning: 'Temps, équilibre et cycles',
    meaningEn: 'Time, Balance and Cycles',
    meaningTifinagh: 'ⴰⴽⵓⴷ, ⴰⵎⵙⴰⵙⴰ ⴷ ⵉⵙⵓⴼⵖⴻⵏ',
    description: "Le sablier — formé de deux triangles opposés par la pointe — symbolise le temps, l'équilibre et les cycles de la vie. Il représente l'union des opposés : masculin et féminin, ciel et terre, passé et futur. Ce motif géométrique orne fréquemment les tapis et les textiles amazighs.",
    descriptionEn: "The hourglass — formed by two opposing triangles at their tips — symbolizes time, balance, and the cycles of life. It represents the union of opposites: masculine and feminine, sky and earth, past and future. This geometric pattern frequently adorns Amazigh carpets and textiles.",
    descriptionTifinagh: "ⵜⴰⵙⵙⴰⵄⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⴽⵓⴷ ⴷ ⵓⵎⵙⴰⵙⴰ.",
    svgId: 'sablier'
  },
  {
    id: 'lion',
    name: 'Lion',
    nameEn: 'Lion',
    tifinagh: 'ⵉⵣⴻⵎ',
    meaning: 'Force et leadership',
    meaningEn: 'Strength and Leadership',
    meaningTifinagh: 'ⵜⴰⵣⵎⴻⵔⵜ ⴷ ⵜⴰⵏⴱⴰⴹⵜ',
    description: "Le lion — izem en tamazight — est un symbole majeur de force, de courage et de leadership. Le lion de l'Atlas, aujourd'hui disparu, était l'animal emblématique de l'Afrique du Nord. Son image représente la puissance protectrice, l'autorité et la noblesse du chef de clan.",
    descriptionEn: "The lion — izem in Tamazight — is a major symbol of strength, courage, and leadership. The Atlas lion, now extinct, was the emblematic animal of North Africa. Its image represents protective power, authority, and the nobility of the clan chief.",
    descriptionTifinagh: "ⵉⵣⴻⵎ ⴷ ⴰⵣⴰⵎⵓⵍ ⵏ ⵜⴰⵣⵎⴻⵔⵜ ⴷ ⵜⴰⵏⴱⴰⴹⵜ.",
    svgId: 'lion'
  },
  {
    id: 'chameau',
    name: 'Chameau',
    nameEn: 'Camel',
    tifinagh: 'ⴰⵍⵖⴻⵎ',
    meaning: 'Endurance et survie',
    meaningEn: 'Endurance and Survival',
    meaningTifinagh: 'ⵜⴰⵙⵎⵉⵔⵜ ⴷ ⵜⵓⴷⴻⵔⵜ',
    description: "Le chameau symbolise l'endurance, la patience et la survie dans les conditions les plus difficiles. Compagnon indispensable des Touaregs dans le Sahara, il représente le voyage, l'adaptation et la capacité à traverser les épreuves. Son image orne les textiles et l'art des peuples nomades.",
    descriptionEn: "The camel symbolizes endurance, patience, and survival in the most difficult conditions. An indispensable companion of the Tuareg in the Sahara, it represents travel, adaptation, and the ability to endure hardship. Its image adorns the textiles and art of nomadic peoples.",
    descriptionTifinagh: "ⴰⵍⵖⴻⵎ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⴰⵙⵎⵉⵔⵜ ⴷ ⵜⵓⴷⴻⵔⵜ ⴳ ⵜⵏⵉⵔⵉ.",
    svgId: 'chameau'
  },
  {
    id: 'fleur',
    name: 'Fleur (Ouarida)',
    nameEn: 'Flower (Ouarida)',
    tifinagh: 'ⵜⴰⵊⵊⴰ',
    meaning: 'Protection et beauté',
    meaningEn: 'Protection and Beauty',
    meaningTifinagh: 'ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵜⴰⵥⵓⵕⵉ',
    description: "La fleur — ouarida — est un symbole de protection contre le mauvais œil et de beauté dans l'art amazigh. Ses pétales en rosace évoquent l'épanouissement et la grâce. Présente sur les poteries et les broderies, elle représente aussi le printemps, le renouveau et la joie de vivre.",
    descriptionEn: "The flower — ouarida — is a symbol of protection against the evil eye and beauty in Amazigh art. Its petals in rosette evoke blossoming and grace. Found on pottery and embroideries, it also represents spring, renewal, and the joy of living.",
    descriptionTifinagh: "ⵜⴰⵊⵊⴰ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵜⴰⵥⵓⵕⵉ.",
    svgId: 'fleur'
  },
  {
    id: 'montagne',
    name: 'Montagne',
    nameEn: 'Mountain',
    tifinagh: 'ⴰⴷⵔⴰⵔ',
    meaning: 'Stabilité et enracinement',
    meaningEn: 'Stability and Rootedness',
    meaningTifinagh: 'ⵜⴰⵣⴷⴻⴳⵜ ⴷ ⵉⵥⵓⵕⴰⵏ',
    description: "La montagne représente la stabilité, l'enracinement et la permanence dans la culture amazighe. L'Atlas, le Rif et les Aurès sont le berceau des peuples amazighs. Ce symbole triangulaire évoque la force immuable, la résistance et le lien profond avec la terre ancestrale.",
    descriptionEn: "The mountain represents stability, rootedness, and permanence in Amazigh culture. The Atlas, the Rif, and the Aures are the cradle of the Amazigh peoples. This triangular symbol evokes immutable strength, resistance, and the deep connection with ancestral land.",
    descriptionTifinagh: "ⴰⴷⵔⴰⵔ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⴰⵣⴷⴻⴳⵜ ⴷ ⵉⵥⵓⵕⴰⵏ.",
    svgId: 'montagne'
  },
  {
    id: 'tortue',
    name: 'Tortue',
    nameEn: 'Turtle',
    tifinagh: 'ⵉⴼⴽⴻⵔ',
    meaning: 'Protection et longévité',
    meaningEn: 'Protection and Longevity',
    meaningTifinagh: 'ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵜⵓⴷⴻⵔⵜ ⵜⴰⵣⴻⴳⵣⴰⵡⵜ',
    description: "La tortue symbolise la protection, la longévité et la sagesse patiente dans la culture amazighe. Sa carapace est un bouclier naturel, métaphore de la protection du foyer. Animal lent mais endurant, elle représente la persévérance et la capacité à porter son monde sur son dos.",
    descriptionEn: "The turtle symbolizes protection, longevity, and patient wisdom in Amazigh culture. Its shell is a natural shield, a metaphor for protecting the home. A slow but enduring animal, it represents perseverance and the ability to carry one's world on one's back.",
    descriptionTifinagh: "ⵉⴼⴽⴻⵔ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⴰⵏⴻⵥⵕⵓⴼ ⴷ ⵜⵓⴷⴻⵔⵜ ⵜⴰⵣⴻⴳⵣⴰⵡⵜ.",
    svgId: 'tortue'
  },
  {
    id: 'escargot',
    name: 'Escargot',
    nameEn: 'Snail',
    tifinagh: 'ⴰⵖⴰⵍⴰⵍ',
    meaning: 'Sagesse lente et stabilité',
    meaningEn: 'Slow Wisdom and Stability',
    meaningTifinagh: 'ⵜⴰⵎⵓⵙⵏⵉ ⴷ ⵜⴰⵣⴷⴻⴳⵜ',
    description: "L'escargot symbolise la sagesse de la lenteur, la stabilité et le foyer que l'on porte avec soi. Sa coquille en spirale évoque les cycles de la vie et la protection. Dans les tatouages amazighs, il représente la patience et la capacité à avancer à son propre rythme sans se perdre.",
    descriptionEn: "The snail symbolizes the wisdom of slowness, stability, and the home one carries with oneself. Its spiral shell evokes life cycles and protection. In Amazigh tattoos, it represents patience and the ability to move at one's own pace without getting lost.",
    descriptionTifinagh: "ⴰⵖⴰⵍⴰⵍ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⴰⵎⵓⵙⵏⵉ ⴷ ⵜⴰⵣⴷⴻⴳⵜ.",
    svgId: 'escargot'
  },
  {
    id: 'olivier',
    name: 'Olivier',
    nameEn: 'Olive Tree',
    tifinagh: 'ⵜⴰⵣⴻⵎⵎⵓⵔⵜ',
    meaning: 'Force tranquille et abondance',
    meaningEn: 'Quiet Strength and Abundance',
    meaningTifinagh: 'ⵜⴰⵣⵎⴻⵔⵜ ⵜⴰⵍⵎⴰⴷⵜ ⴷ ⵜⴰⴳⴳⴰⵔⵜ',
    description: "L'olivier occupe une place primordiale dans les régions montagneuses d'Afrique du Nord. Symbole de force tranquille, d'abondance et de paix, son huile représente la force vitale. Arbre millénaire, il incarne l'enracinement et la prospérité durable des communautés amazighes.",
    descriptionEn: "The olive tree holds a primordial place in the mountainous regions of North Africa. Symbol of quiet strength, abundance, and peace, its oil represents vital force. A millennial tree, it embodies the rootedness and lasting prosperity of Amazigh communities.",
    descriptionTifinagh: "ⵜⴰⵣⴻⵎⵎⵓⵔⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⵜⴰⵣⵎⴻⵔⵜ ⵜⴰⵍⵎⴰⴷⵜ ⴷ ⵜⴰⴳⴳⴰⵔⵜ.",
    svgId: 'olivier'
  },
  {
    id: 'taureau',
    name: 'Taureau',
    nameEn: 'Bull',
    tifinagh: 'ⴰⵣⴳⴻⵔ',
    meaning: 'Force masculine et fécondité',
    meaningEn: 'Masculine Strength and Fertility',
    meaningTifinagh: 'ⵜⴰⵣⵎⴻⵔⵜ ⵏ ⵓⵔⴳⴰⵣ ⴷ ⵜⵓⵙⵓⵜ',
    description: "Le taureau représente la force masculine, la puissance reproductrice et la fertilité de la terre dans la cosmologie amazighe. Sur les poteries kabyles, il est souvent associé à la lune, formant le couple taureau-lune — pendant cosmique du couple ciel-terre symbolisant la fertilité universelle.",
    descriptionEn: "The bull represents masculine strength, reproductive power, and the fertility of the land in Amazigh cosmology. On Kabyle pottery, it is often associated with the moon, forming the bull-moon pair — a cosmic counterpart of the sky-earth couple symbolizing universal fertility.",
    descriptionTifinagh: "ⴰⵣⴳⴻⵔ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⴰⵣⵎⴻⵔⵜ ⵏ ⵓⵔⴳⴰⵣ ⴷ ⵜⵓⵙⵓⵜ.",
    svgId: 'taureau'
  },
  {
    id: 'ble',
    name: 'Blé',
    nameEn: 'Wheat',
    tifinagh: 'ⵉⵔⴷⴻⵏ',
    meaning: 'Vie, mort et renaissance',
    meaningEn: 'Life, Death and Rebirth',
    meaningTifinagh: 'ⵜⵓⴷⴻⵔⵜ, ⵜⴰⵎⴻⵜⵜⴰⵏⵜ ⴷ ⵜⴰⵍⴰⵍⵉⵜ',
    description: "Le blé symbolise à la fois la vie et la mort dans la symbolique amazighe. Semé, il meurt dans la terre pour renaître sous forme d'épi. Il représente le cycle des saisons, la subsistance et le lien profond entre le peuple amazigh et sa terre nourricière.",
    descriptionEn: "Wheat symbolizes both life and death in Amazigh symbolism. Sown, it dies in the earth to be reborn as a spike. It represents the cycle of seasons, subsistence, and the deep bond between the Amazigh people and their nurturing land.",
    descriptionTifinagh: "ⵉⵔⴷⴻⵏ ⴰⵔ ⵙⵎⴻⴽⵜⵉⵏ ⵜⵓⴷⴻⵔⵜ ⴷ ⵜⴰⵎⴻⵜⵜⴰⵏⵜ ⴷ ⵜⴰⵍⴰⵍⵉⵜ.",
    svgId: 'ble'
  },
  {
    id: 'rosace',
    name: 'Rosace / Étoile à 6 branches',
    nameEn: 'Rosette / Six-Pointed Star',
    tifinagh: 'ⵜⴰⵡⵙⵙⴰⵔⵜ',
    meaning: "Union des opposés",
    meaningEn: 'Union of Opposites',
    meaningTifinagh: 'ⵜⴰⵎⵓⵏⵜ ⵏ ⵉⵎⵣⴰⵔⴰⵢⴻⵏ',
    description: "La rosace — étoile à six branches formée de deux triangles inversés — symbolise l'union des forces opposées : le masculin (triangle vers le haut, feu, virilité) et le féminin (triangle vers le bas, eau, fécondité). Elle incarne l'équilibre parfait et l'harmonie cosmique.",
    descriptionEn: "The rosette — a six-pointed star formed by two inverted triangles — symbolizes the union of opposing forces: the masculine (upward triangle, fire, virility) and the feminine (downward triangle, water, fecundity). It embodies perfect balance and cosmic harmony.",
    descriptionTifinagh: "ⵜⴰⵡⵙⵙⴰⵔⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⵜⴰⵎⵓⵏⵜ ⵏ ⵉⵎⵣⴰⵔⴰⵢⴻⵏ.",
    svgId: 'rosace'
  },
  {
    id: 'perdrix',
    name: 'Yeux de perdrix',
    nameEn: 'Partridge Eyes',
    tifinagh: 'ⵜⵉⵟⵟⴰⵡⵉⵏ ⵏ ⵜⵙⴻⴽⴽⵓⵔⵜ',
    meaning: 'Beauté et grâce féminine',
    meaningEn: 'Beauty and Feminine Grace',
    meaningTifinagh: 'ⵜⴰⵥⵓⵕⵉ ⴷ ⵜⴰⵎⵍⵉⵍⵜ',
    description: "Les « yeux de perdrix » sont un motif décoratif récurrent dans les tapis et tatouages amazighs. Formés de cercles concentriques en damier, ils symbolisent la beauté féminine, la grâce et la vigilance. La perdrix, oiseau élégant, est une métaphore de la femme amazighe.",
    descriptionEn: "'Partridge eyes' are a recurring decorative pattern in Amazigh carpets and tattoos. Formed of concentric checkered circles, they symbolize feminine beauty, grace, and vigilance. The partridge, an elegant bird, is a metaphor for the Amazigh woman.",
    descriptionTifinagh: "ⵜⵉⵟⵟⴰⵡⵉⵏ ⵏ ⵜⵙⴻⴽⴽⵓⵔⵜ ⴰⵔ ⵙⵎⴻⴽⵜⵉⵏⵜ ⵜⴰⵥⵓⵕⵉ ⴷ ⵜⴰⵎⵍⵉⵍⵜ.",
    svgId: 'perdrix'
  },
  {
    id: 'carre',
    name: 'Carré',
    nameEn: 'Square',
    tifinagh: 'ⴰⵎⴽⵓⵥⴰⵏ',
    meaning: 'La maison et le foyer',
    meaningEn: 'The House and Home',
    meaningTifinagh: 'ⵜⵉⴳⴻⵎⵎⵉ ⴷ ⵓⵎⴻⵙⵙⵓ',
    description: "Le carré représente la maison, le foyer et la famille dans la symbolique amazighe. Ses quatre côtés égaux évoquent la stabilité et l'ordre. Deux carrés superposés symbolisent le combat de Dieu contre les ténèbres. C'est l'un des motifs de base des tatouages faciaux féminins.",
    descriptionEn: "The square represents the house, the home, and the family in Amazigh symbolism. Its four equal sides evoke stability and order. Two superimposed squares symbolize the battle of God against darkness. It is one of the basic patterns of women's facial tattoos.",
    descriptionTifinagh: "ⴰⵎⴽⵓⵥⴰⵏ ⴰⵔ ⵉⵙⵎⴻⴽⵜⵉ ⵜⵉⴳⴻⵎⵎⵉ ⴷ ⵓⵎⴻⵙⵙⵓ.",
    svgId: 'carre'
  },
  {
    id: 'graine',
    name: 'Graine',
    nameEn: 'Seed',
    tifinagh: 'ⵜⴰⵎⵥⵉⵏⵜ',
    meaning: 'Semence de vie et fécondité',
    meaningEn: 'Seed of Life and Fertility',
    meaningTifinagh: 'ⵜⴰⵎⵥⵉⵏⵜ ⵏ ⵜⵓⴷⴻⵔⵜ ⴷ ⵜⵓⵙⵓⵜ',
    description: "La graine symbolise la semence, le début de toute vie et le potentiel infini de croissance. Dans les tatouages amazighs, elle représente la fécondité et la transmission de la vie. Les points isolés ou en groupes sur les poteries et textiles évoquent les graines semées dans la terre.",
    descriptionEn: "The seed symbolizes the beginning of all life and the infinite potential for growth. In Amazigh tattoos, it represents fertility and the transmission of life. Isolated or grouped dots on pottery and textiles evoke seeds sown in the earth.",
    descriptionTifinagh: "ⵜⴰⵎⵥⵉⵏⵜ ⴰⵔ ⵜⵙⵎⴻⴽⵜⵉ ⵜⵓⵙⵓⵜ ⴷ ⵜⵉⵣⵉ ⵏ ⵜⵓⴷⴻⵔⵜ.",
    svgId: 'graine'
  }
];

// ===== Tifinagh Alphabet (IRCAM Neo-Tifinagh Standard) =====
const ALPHABET = [
  { letter: 'ⴰ', name: 'Ya', translit: 'a', phonetic: 'a' },
  { letter: 'ⴱ', name: 'Yab', translit: 'b', phonetic: 'b' },
  { letter: 'ⴳ', name: 'Yag', translit: 'g', phonetic: 'g' },
  { letter: 'ⴷ', name: 'Yad', translit: 'd', phonetic: 'd' },
  { letter: 'ⴹ', name: 'Yaḍ', translit: 'ḍ', phonetic: 'ḍ (emphatic d)' },
  { letter: 'ⴻ', name: 'Yey', translit: 'e', phonetic: 'e (schwa)' },
  { letter: 'ⴼ', name: 'Yaf', translit: 'f', phonetic: 'f' },
  { letter: 'ⴽ', name: 'Yak', translit: 'k', phonetic: 'k' },
  { letter: 'ⴽⵯ', name: 'Yakʷ', translit: 'kʷ', phonetic: 'kʷ (labialized k)' },
  { letter: 'ⵀ', name: 'Yah', translit: 'h', phonetic: 'h' },
  { letter: 'ⵃ', name: 'Yaḥ', translit: 'ḥ', phonetic: 'ḥ (pharyngeal)' },
  { letter: 'ⵄ', name: 'Yaɛ', translit: 'ɛ', phonetic: 'ɛ (pharyngeal)' },
  { letter: 'ⵅ', name: 'Yax', translit: 'x', phonetic: 'x (kh)' },
  { letter: 'ⵇ', name: 'Yaq', translit: 'q', phonetic: 'q' },
  { letter: 'ⵉ', name: 'Yi', translit: 'i', phonetic: 'i' },
  { letter: 'ⵊ', name: 'Yaj', translit: 'j', phonetic: 'ʒ (j)' },
  { letter: 'ⵍ', name: 'Yal', translit: 'l', phonetic: 'l' },
  { letter: 'ⵎ', name: 'Yam', translit: 'm', phonetic: 'm' },
  { letter: 'ⵏ', name: 'Yan', translit: 'n', phonetic: 'n' },
  { letter: 'ⵓ', name: 'Yu', translit: 'u', phonetic: 'u' },
  { letter: 'ⵔ', name: 'Yar', translit: 'r', phonetic: 'r' },
  { letter: 'ⵕ', name: 'Yaṛ', translit: 'ṛ', phonetic: 'ṛ (emphatic r)' },
  { letter: 'ⵖ', name: 'Yaɣ', translit: 'ɣ', phonetic: 'ɣ (gh)' },
  { letter: 'ⵙ', name: 'Yas', translit: 's', phonetic: 's' },
  { letter: 'ⵚ', name: 'Yaṣ', translit: 'ṣ', phonetic: 'ṣ (emphatic s)' },
  { letter: 'ⵛ', name: 'Yac', translit: 'c', phonetic: 'ʃ (ch/sh)' },
  { letter: 'ⵜ', name: 'Yat', translit: 't', phonetic: 't' },
  { letter: 'ⵟ', name: 'Yaṭ', translit: 'ṭ', phonetic: 'ṭ (emphatic t)' },
  { letter: 'ⵡ', name: 'Yaw', translit: 'w', phonetic: 'w' },
  { letter: 'ⵢ', name: 'Yay', translit: 'y', phonetic: 'y' },
  { letter: 'ⵣ', name: 'Yaz', translit: 'z', phonetic: 'z' },
  { letter: 'ⵥ', name: 'Yaẓ', translit: 'ẓ', phonetic: 'ẓ (emphatic z)' },
  { letter: 'ⵯ', name: 'Labialisation', translit: 'ʷ', phonetic: 'ʷ (labialisation mark)' }
];
